env:
  browser: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - prettier

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react-refresh

rules:
  react-refresh/only-export-components: warn
